site_name: pixltsnorm
site_url: https://pixltsnorm.sefa.ai
repo_url: https://github.com/iosefa/pixltsnorm

theme:
    name: material
    palette:
        primary: green
        accent: deep-orange
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
    custom_dir: overrides

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: true
        execute: false
        ignore_h1_titles: true

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage:
        - usage/landsat-timeseries-creation.md
        - usage/timeseries-harmonization.md
        - usage/timeseries-harmonization-global.md
        - usage/timeseries-harmonization-local.md
    - Contributing: contributing.md
    - Changelog: https://github.com/iosefa/pixltsnorm/releases
    - Report Issues: https://github.com/iosefa/pixltsnorm/issues
    - Examples:
        - examples/getting-started-timeseries-normalization.ipynb
        - examples/global-ndvi-harmonization.ipynb
        - examples/local-ndvi-harmonization.ipynb
        - examples/create-ndvi-timeseries-with-earthengine.ipynb
    - API Reference:
        - harmonize module: api/harmonize.md
        - dataframe_harmonize module: api/dataframe_harmonize.md
        - models module: api/models.md
        - utils module: api/utils.md
        - earth engine:
            - api/earth_engine/landsat.md

extra_css:
    - overrides/custom.css

extra_javascript:
 - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js